[pytest]
markers =
    smoke: tests críticos que verifican funcionalidad básica
    regression: suite completa de regresión
    login: tests relacionados al módulo de login
    cart: tests relacionados al carrito y checkout

addopts = --alluredir=allure-results --clean-alluredir
